targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: stdlib|lib/schema.graphql
          type_overrides:
            uuid:
              name: UuidType
              import: 'package:stdlib/uuid_type.dart'
            timestamptz:
              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: stdlib|lib/schema.graphql
          type_overrides:
            uuid:
              name: UuidType
              import: 'package:stdlib/uuid_type.dart'
            timestamptz:
              name: DateTime
          custom_serializers:
          - import: 'package:stdlib/uuid_type.dart'
            name: UuidTypeSerializer
          - import: 'package:stdlib/datetime_type_converter.dart'
            name: DateTimeSerializer
