name: stdlib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # serialization
  uuid: ^4.3.2

  # gql
  ferry: ^0.16.0+1
  gql_http_link: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ferry_generator: ^0.10.0
  build_runner: ^2.4.8

flutter:
