// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface CloudnativepgProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: CloudnativepgValues;
}

export class Cloudnativepg extends Construct {
  public constructor(scope: Construct, id: string, props: CloudnativepgProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_CloudnativepgValues(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'cloudnative-pg',
      repo: 'https://cloudnative-pg.io/charts',
      version: '0.26.1',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema cloudnative-pg
 */
export interface CloudnativepgValues {
  /**
   * @schema cloudnative-pg#additionalArgs
   */
  readonly additionalArgs?: any[];

  /**
   * @schema cloudnative-pg#additionalEnv
   */
  readonly additionalEnv?: any[];

  /**
   * @schema cloudnative-pg#affinity
   */
  readonly affinity?: any;

  /**
   * @schema cloudnative-pg#commonAnnotations
   */
  readonly commonAnnotations?: any;

  /**
   * @schema cloudnative-pg#config
   */
  readonly config?: CloudnativePgConfig;

  /**
   * @schema cloudnative-pg#containerSecurityContext
   */
  readonly containerSecurityContext?: CloudnativePgContainerSecurityContext;

  /**
   * @schema cloudnative-pg#crds
   */
  readonly crds?: CloudnativePgCrds;

  /**
   * @schema cloudnative-pg#dnsPolicy
   */
  readonly dnsPolicy?: string;

  /**
   * @schema cloudnative-pg#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema cloudnative-pg#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema cloudnative-pg#image
   */
  readonly image?: CloudnativePgImage;

  /**
   * @schema cloudnative-pg#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema cloudnative-pg#monitoring
   */
  readonly monitoring?: CloudnativePgMonitoring;

  /**
   * @schema cloudnative-pg#monitoringQueriesConfigMap
   */
  readonly monitoringQueriesConfigMap?: CloudnativePgMonitoringQueriesConfigMap;

  /**
   * @schema cloudnative-pg#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema cloudnative-pg#namespaceOverride
   */
  readonly namespaceOverride?: string;

  /**
   * @schema cloudnative-pg#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema cloudnative-pg#podAnnotations
   */
  readonly podAnnotations?: any;

  /**
   * @schema cloudnative-pg#podLabels
   */
  readonly podLabels?: any;

  /**
   * @schema cloudnative-pg#podSecurityContext
   */
  readonly podSecurityContext?: CloudnativePgPodSecurityContext;

  /**
   * @schema cloudnative-pg#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema cloudnative-pg#rbac
   */
  readonly rbac?: CloudnativePgRbac;

  /**
   * @schema cloudnative-pg#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema cloudnative-pg#resources
   */
  readonly resources?: any;

  /**
   * @schema cloudnative-pg#service
   */
  readonly service?: CloudnativePgService;

  /**
   * @schema cloudnative-pg#serviceAccount
   */
  readonly serviceAccount?: CloudnativePgServiceAccount;

  /**
   * @schema cloudnative-pg#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema cloudnative-pg#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * @schema cloudnative-pg#updateStrategy
   */
  readonly updateStrategy?: any;

  /**
   * @schema cloudnative-pg#webhook
   */
  readonly webhook?: CloudnativePgWebhook;

  /**
   * @schema cloudnative-pg#cluster
   */
  readonly cluster?: { [key: string]: any };

  /**
   * @schema cloudnative-pg#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema cloudnative-pg#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativepgValues' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativepgValues(obj: CloudnativepgValues | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'additionalArgs': obj.additionalArgs?.map(y => y),
    'additionalEnv': obj.additionalEnv?.map(y => y),
    'affinity': obj.affinity,
    'commonAnnotations': obj.commonAnnotations,
    'config': toJson_CloudnativePgConfig(obj.config),
    'containerSecurityContext': toJson_CloudnativePgContainerSecurityContext(obj.containerSecurityContext),
    'crds': toJson_CloudnativePgCrds(obj.crds),
    'dnsPolicy': obj.dnsPolicy,
    'fullnameOverride': obj.fullnameOverride,
    'hostNetwork': obj.hostNetwork,
    'image': toJson_CloudnativePgImage(obj.image),
    'imagePullSecrets': obj.imagePullSecrets?.map(y => y),
    'monitoring': toJson_CloudnativePgMonitoring(obj.monitoring),
    'monitoringQueriesConfigMap': toJson_CloudnativePgMonitoringQueriesConfigMap(obj.monitoringQueriesConfigMap),
    'nameOverride': obj.nameOverride,
    'namespaceOverride': obj.namespaceOverride,
    'nodeSelector': obj.nodeSelector,
    'podAnnotations': obj.podAnnotations,
    'podLabels': obj.podLabels,
    'podSecurityContext': toJson_CloudnativePgPodSecurityContext(obj.podSecurityContext),
    'priorityClassName': obj.priorityClassName,
    'rbac': toJson_CloudnativePgRbac(obj.rbac),
    'replicaCount': obj.replicaCount,
    'resources': obj.resources,
    'service': toJson_CloudnativePgService(obj.service),
    'serviceAccount': toJson_CloudnativePgServiceAccount(obj.serviceAccount),
    'tolerations': obj.tolerations?.map(y => y),
    'topologySpreadConstraints': obj.topologySpreadConstraints?.map(y => y),
    'updateStrategy': obj.updateStrategy,
    'webhook': toJson_CloudnativePgWebhook(obj.webhook),
    'cluster': ((obj.cluster) === undefined) ? undefined : (Object.entries(obj.cluster).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'global': ((obj.global) === undefined) ? undefined : (Object.entries(obj.global).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgConfig
 */
export interface CloudnativePgConfig {
  /**
   * @schema CloudnativePgConfig#clusterWide
   */
  readonly clusterWide?: boolean;

  /**
   * @schema CloudnativePgConfig#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgConfig#data
   */
  readonly data?: any;

  /**
   * @schema CloudnativePgConfig#maxConcurrentReconciles
   */
  readonly maxConcurrentReconciles?: number;

  /**
   * @schema CloudnativePgConfig#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgConfig#secret
   */
  readonly secret?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgConfig#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgConfig(obj: CloudnativePgConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clusterWide': obj.clusterWide,
    'create': obj.create,
    'data': obj.data,
    'maxConcurrentReconciles': obj.maxConcurrentReconciles,
    'name': obj.name,
    'secret': obj.secret,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgContainerSecurityContext
 */
export interface CloudnativePgContainerSecurityContext {
  /**
   * @schema CloudnativePgContainerSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * @schema CloudnativePgContainerSecurityContext#capabilities
   */
  readonly capabilities?: CloudnativePgContainerSecurityContextCapabilities;

  /**
   * @schema CloudnativePgContainerSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * @schema CloudnativePgContainerSecurityContext#runAsGroup
   */
  readonly runAsGroup?: number;

  /**
   * @schema CloudnativePgContainerSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * @schema CloudnativePgContainerSecurityContext#seccompProfile
   */
  readonly seccompProfile?: CloudnativePgContainerSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgContainerSecurityContext' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgContainerSecurityContext(obj: CloudnativePgContainerSecurityContext | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allowPrivilegeEscalation': obj.allowPrivilegeEscalation,
    'capabilities': toJson_CloudnativePgContainerSecurityContextCapabilities(obj.capabilities),
    'readOnlyRootFilesystem': obj.readOnlyRootFilesystem,
    'runAsGroup': obj.runAsGroup,
    'runAsUser': obj.runAsUser,
    'seccompProfile': toJson_CloudnativePgContainerSecurityContextSeccompProfile(obj.seccompProfile),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgCrds
 */
export interface CloudnativePgCrds {
  /**
   * @schema CloudnativePgCrds#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgCrds#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgCrds' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgCrds(obj: CloudnativePgCrds | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgImage
 */
export interface CloudnativePgImage {
  /**
   * @schema CloudnativePgImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema CloudnativePgImage#repository
   */
  readonly repository?: string;

  /**
   * @schema CloudnativePgImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgImage' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgImage(obj: CloudnativePgImage | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'pullPolicy': obj.pullPolicy,
    'repository': obj.repository,
    'tag': obj.tag,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgMonitoring
 */
export interface CloudnativePgMonitoring {
  /**
   * @schema CloudnativePgMonitoring#grafanaDashboard
   */
  readonly grafanaDashboard?: CloudnativePgMonitoringGrafanaDashboard;

  /**
   * @schema CloudnativePgMonitoring#podMonitorAdditionalLabels
   */
  readonly podMonitorAdditionalLabels?: any;

  /**
   * @schema CloudnativePgMonitoring#podMonitorEnabled
   */
  readonly podMonitorEnabled?: boolean;

  /**
   * @schema CloudnativePgMonitoring#podMonitorMetricRelabelings
   */
  readonly podMonitorMetricRelabelings?: any[];

  /**
   * @schema CloudnativePgMonitoring#podMonitorRelabelings
   */
  readonly podMonitorRelabelings?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoring#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgMonitoring' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgMonitoring(obj: CloudnativePgMonitoring | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'grafanaDashboard': toJson_CloudnativePgMonitoringGrafanaDashboard(obj.grafanaDashboard),
    'podMonitorAdditionalLabels': obj.podMonitorAdditionalLabels,
    'podMonitorEnabled': obj.podMonitorEnabled,
    'podMonitorMetricRelabelings': obj.podMonitorMetricRelabelings?.map(y => y),
    'podMonitorRelabelings': obj.podMonitorRelabelings?.map(y => y),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgMonitoringQueriesConfigMap
 */
export interface CloudnativePgMonitoringQueriesConfigMap {
  /**
   * @schema CloudnativePgMonitoringQueriesConfigMap#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgMonitoringQueriesConfigMap#queries
   */
  readonly queries?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoringQueriesConfigMap#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgMonitoringQueriesConfigMap' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgMonitoringQueriesConfigMap(obj: CloudnativePgMonitoringQueriesConfigMap | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'queries': obj.queries,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgPodSecurityContext
 */
export interface CloudnativePgPodSecurityContext {
  /**
   * @schema CloudnativePgPodSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * @schema CloudnativePgPodSecurityContext#seccompProfile
   */
  readonly seccompProfile?: CloudnativePgPodSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgPodSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgPodSecurityContext' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgPodSecurityContext(obj: CloudnativePgPodSecurityContext | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'runAsNonRoot': obj.runAsNonRoot,
    'seccompProfile': toJson_CloudnativePgPodSecurityContextSeccompProfile(obj.seccompProfile),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgRbac
 */
export interface CloudnativePgRbac {
  /**
   * @schema CloudnativePgRbac#aggregateClusterRoles
   */
  readonly aggregateClusterRoles?: boolean;

  /**
   * @schema CloudnativePgRbac#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgRbac' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgRbac(obj: CloudnativePgRbac | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'aggregateClusterRoles': obj.aggregateClusterRoles,
    'create': obj.create,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgService
 */
export interface CloudnativePgService {
  /**
   * @schema CloudnativePgService#ipFamilies
   */
  readonly ipFamilies?: any[];

  /**
   * @schema CloudnativePgService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: string;

  /**
   * @schema CloudnativePgService#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgService#port
   */
  readonly port?: number;

  /**
   * @schema CloudnativePgService#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgService' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgService(obj: CloudnativePgService | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ipFamilies': obj.ipFamilies?.map(y => y),
    'ipFamilyPolicy': obj.ipFamilyPolicy,
    'name': obj.name,
    'port': obj.port,
    'type': obj.type,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgServiceAccount
 */
export interface CloudnativePgServiceAccount {
  /**
   * @schema CloudnativePgServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgServiceAccount#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgServiceAccount' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgServiceAccount(obj: CloudnativePgServiceAccount | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhook
 */
export interface CloudnativePgWebhook {
  /**
   * @schema CloudnativePgWebhook#livenessProbe
   */
  readonly livenessProbe?: CloudnativePgWebhookLivenessProbe;

  /**
   * @schema CloudnativePgWebhook#mutating
   */
  readonly mutating?: CloudnativePgWebhookMutating;

  /**
   * @schema CloudnativePgWebhook#port
   */
  readonly port?: number;

  /**
   * @schema CloudnativePgWebhook#readinessProbe
   */
  readonly readinessProbe?: CloudnativePgWebhookReadinessProbe;

  /**
   * @schema CloudnativePgWebhook#startupProbe
   */
  readonly startupProbe?: CloudnativePgWebhookStartupProbe;

  /**
   * @schema CloudnativePgWebhook#validating
   */
  readonly validating?: CloudnativePgWebhookValidating;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhook#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhook' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhook(obj: CloudnativePgWebhook | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'livenessProbe': toJson_CloudnativePgWebhookLivenessProbe(obj.livenessProbe),
    'mutating': toJson_CloudnativePgWebhookMutating(obj.mutating),
    'port': obj.port,
    'readinessProbe': toJson_CloudnativePgWebhookReadinessProbe(obj.readinessProbe),
    'startupProbe': toJson_CloudnativePgWebhookStartupProbe(obj.startupProbe),
    'validating': toJson_CloudnativePgWebhookValidating(obj.validating),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgContainerSecurityContextCapabilities
 */
export interface CloudnativePgContainerSecurityContextCapabilities {
  /**
   * @schema CloudnativePgContainerSecurityContextCapabilities#drop
   */
  readonly drop?: string[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContextCapabilities#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgContainerSecurityContextCapabilities' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgContainerSecurityContextCapabilities(obj: CloudnativePgContainerSecurityContextCapabilities | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'drop': obj.drop?.map(y => y),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgContainerSecurityContextSeccompProfile
 */
export interface CloudnativePgContainerSecurityContextSeccompProfile {
  /**
   * @schema CloudnativePgContainerSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgContainerSecurityContextSeccompProfile' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgContainerSecurityContextSeccompProfile(obj: CloudnativePgContainerSecurityContextSeccompProfile | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'type': obj.type,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgMonitoringGrafanaDashboard
 */
export interface CloudnativePgMonitoringGrafanaDashboard {
  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#annotations
   */
  readonly annotations?: any;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#configMapName
   */
  readonly configMapName?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#labels
   */
  readonly labels?: any;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#namespace
   */
  readonly namespace?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#sidecarLabel
   */
  readonly sidecarLabel?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#sidecarLabelValue
   */
  readonly sidecarLabelValue?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoringGrafanaDashboard#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgMonitoringGrafanaDashboard' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgMonitoringGrafanaDashboard(obj: CloudnativePgMonitoringGrafanaDashboard | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'annotations': obj.annotations,
    'configMapName': obj.configMapName,
    'create': obj.create,
    'labels': obj.labels,
    'namespace': obj.namespace,
    'sidecarLabel': obj.sidecarLabel,
    'sidecarLabelValue': obj.sidecarLabelValue,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgPodSecurityContextSeccompProfile
 */
export interface CloudnativePgPodSecurityContextSeccompProfile {
  /**
   * @schema CloudnativePgPodSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgPodSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgPodSecurityContextSeccompProfile' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgPodSecurityContextSeccompProfile(obj: CloudnativePgPodSecurityContextSeccompProfile | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'type': obj.type,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhookLivenessProbe
 */
export interface CloudnativePgWebhookLivenessProbe {
  /**
   * @schema CloudnativePgWebhookLivenessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookLivenessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhookLivenessProbe' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhookLivenessProbe(obj: CloudnativePgWebhookLivenessProbe | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'initialDelaySeconds': obj.initialDelaySeconds,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhookMutating
 */
export interface CloudnativePgWebhookMutating {
  /**
   * @schema CloudnativePgWebhookMutating#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgWebhookMutating#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookMutating#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhookMutating' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhookMutating(obj: CloudnativePgWebhookMutating | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'failurePolicy': obj.failurePolicy,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhookReadinessProbe
 */
export interface CloudnativePgWebhookReadinessProbe {
  /**
   * @schema CloudnativePgWebhookReadinessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhookReadinessProbe' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhookReadinessProbe(obj: CloudnativePgWebhookReadinessProbe | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'initialDelaySeconds': obj.initialDelaySeconds,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhookStartupProbe
 */
export interface CloudnativePgWebhookStartupProbe {
  /**
   * @schema CloudnativePgWebhookStartupProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema CloudnativePgWebhookStartupProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookStartupProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhookStartupProbe' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhookStartupProbe(obj: CloudnativePgWebhookStartupProbe | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'failureThreshold': obj.failureThreshold,
    'periodSeconds': obj.periodSeconds,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudnativePgWebhookValidating
 */
export interface CloudnativePgWebhookValidating {
  /**
   * @schema CloudnativePgWebhookValidating#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgWebhookValidating#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookValidating#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'CloudnativePgWebhookValidating' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudnativePgWebhookValidating(obj: CloudnativePgWebhookValidating | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'failurePolicy': obj.failurePolicy,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

