// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface CloudnativepgProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: CloudnativepgValues;
}

export class Cloudnativepg extends Construct {
  public constructor(scope: Construct, id: string, props: CloudnativepgProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const { additionalValues, ...valuesWithoutAdditionalValues } = props.values;
      updatedProps = {
        ...props,
        values: {
          ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
          ...additionalValues,
        },
      };
    }

    const finalProps: HelmProps = {
      chart: 'cloudnative-pg',
      repo: 'https://cloudnative-pg.github.io/charts',
      version: '0.26.0',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema cloudnative-pg
 */
export interface CloudnativepgValues {
  /**
   * @schema cloudnative-pg#additionalArgs
   */
  readonly additionalArgs?: any[];

  /**
   * @schema cloudnative-pg#additionalEnv
   */
  readonly additionalEnv?: any[];

  /**
   * @schema cloudnative-pg#affinity
   */
  readonly affinity?: any;

  /**
   * @schema cloudnative-pg#commonAnnotations
   */
  readonly commonAnnotations?: any;

  /**
   * @schema cloudnative-pg#config
   */
  readonly config?: CloudnativePgConfig;

  /**
   * @schema cloudnative-pg#containerSecurityContext
   */
  readonly containerSecurityContext?: CloudnativePgContainerSecurityContext;

  /**
   * @schema cloudnative-pg#crds
   */
  readonly crds?: CloudnativePgCrds;

  /**
   * @schema cloudnative-pg#dnsPolicy
   */
  readonly dnsPolicy?: string;

  /**
   * @schema cloudnative-pg#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema cloudnative-pg#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema cloudnative-pg#image
   */
  readonly image?: CloudnativePgImage;

  /**
   * @schema cloudnative-pg#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema cloudnative-pg#monitoring
   */
  readonly monitoring?: CloudnativePgMonitoring;

  /**
   * @schema cloudnative-pg#monitoringQueriesConfigMap
   */
  readonly monitoringQueriesConfigMap?: CloudnativePgMonitoringQueriesConfigMap;

  /**
   * @schema cloudnative-pg#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema cloudnative-pg#namespaceOverride
   */
  readonly namespaceOverride?: string;

  /**
   * @schema cloudnative-pg#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema cloudnative-pg#podAnnotations
   */
  readonly podAnnotations?: any;

  /**
   * @schema cloudnative-pg#podLabels
   */
  readonly podLabels?: any;

  /**
   * @schema cloudnative-pg#podSecurityContext
   */
  readonly podSecurityContext?: CloudnativePgPodSecurityContext;

  /**
   * @schema cloudnative-pg#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema cloudnative-pg#rbac
   */
  readonly rbac?: CloudnativePgRbac;

  /**
   * @schema cloudnative-pg#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema cloudnative-pg#resources
   */
  readonly resources?: any;

  /**
   * @schema cloudnative-pg#service
   */
  readonly service?: CloudnativePgService;

  /**
   * @schema cloudnative-pg#serviceAccount
   */
  readonly serviceAccount?: CloudnativePgServiceAccount;

  /**
   * @schema cloudnative-pg#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema cloudnative-pg#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * @schema cloudnative-pg#updateStrategy
   */
  readonly updateStrategy?: any;

  /**
   * @schema cloudnative-pg#webhook
   */
  readonly webhook?: CloudnativePgWebhook;

  /**
   * @schema cloudnative-pg#cluster
   */
  readonly cluster?: { [key: string]: any };

  /**
   * @schema cloudnative-pg#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema cloudnative-pg#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgConfig
 */
export interface CloudnativePgConfig {
  /**
   * @schema CloudnativePgConfig#clusterWide
   */
  readonly clusterWide?: boolean;

  /**
   * @schema CloudnativePgConfig#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgConfig#data
   */
  readonly data?: any;

  /**
   * @schema CloudnativePgConfig#maxConcurrentReconciles
   */
  readonly maxConcurrentReconciles?: number;

  /**
   * @schema CloudnativePgConfig#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgConfig#secret
   */
  readonly secret?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgConfig#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgContainerSecurityContext
 */
export interface CloudnativePgContainerSecurityContext {
  /**
   * @schema CloudnativePgContainerSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * @schema CloudnativePgContainerSecurityContext#capabilities
   */
  readonly capabilities?: CloudnativePgContainerSecurityContextCapabilities;

  /**
   * @schema CloudnativePgContainerSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * @schema CloudnativePgContainerSecurityContext#runAsGroup
   */
  readonly runAsGroup?: number;

  /**
   * @schema CloudnativePgContainerSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * @schema CloudnativePgContainerSecurityContext#seccompProfile
   */
  readonly seccompProfile?: CloudnativePgContainerSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgCrds
 */
export interface CloudnativePgCrds {
  /**
   * @schema CloudnativePgCrds#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgCrds#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgImage
 */
export interface CloudnativePgImage {
  /**
   * @schema CloudnativePgImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema CloudnativePgImage#repository
   */
  readonly repository?: string;

  /**
   * @schema CloudnativePgImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgMonitoring
 */
export interface CloudnativePgMonitoring {
  /**
   * @schema CloudnativePgMonitoring#grafanaDashboard
   */
  readonly grafanaDashboard?: CloudnativePgMonitoringGrafanaDashboard;

  /**
   * @schema CloudnativePgMonitoring#podMonitorAdditionalLabels
   */
  readonly podMonitorAdditionalLabels?: any;

  /**
   * @schema CloudnativePgMonitoring#podMonitorEnabled
   */
  readonly podMonitorEnabled?: boolean;

  /**
   * @schema CloudnativePgMonitoring#podMonitorMetricRelabelings
   */
  readonly podMonitorMetricRelabelings?: any[];

  /**
   * @schema CloudnativePgMonitoring#podMonitorRelabelings
   */
  readonly podMonitorRelabelings?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoring#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgMonitoringQueriesConfigMap
 */
export interface CloudnativePgMonitoringQueriesConfigMap {
  /**
   * @schema CloudnativePgMonitoringQueriesConfigMap#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgMonitoringQueriesConfigMap#queries
   */
  readonly queries?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoringQueriesConfigMap#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgPodSecurityContext
 */
export interface CloudnativePgPodSecurityContext {
  /**
   * @schema CloudnativePgPodSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * @schema CloudnativePgPodSecurityContext#seccompProfile
   */
  readonly seccompProfile?: CloudnativePgPodSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgPodSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgRbac
 */
export interface CloudnativePgRbac {
  /**
   * @schema CloudnativePgRbac#aggregateClusterRoles
   */
  readonly aggregateClusterRoles?: boolean;

  /**
   * @schema CloudnativePgRbac#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgService
 */
export interface CloudnativePgService {
  /**
   * @schema CloudnativePgService#ipFamilies
   */
  readonly ipFamilies?: any[];

  /**
   * @schema CloudnativePgService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: string;

  /**
   * @schema CloudnativePgService#name
   */
  readonly name?: string;

  /**
   * @schema CloudnativePgService#port
   */
  readonly port?: number;

  /**
   * @schema CloudnativePgService#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgServiceAccount
 */
export interface CloudnativePgServiceAccount {
  /**
   * @schema CloudnativePgServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgServiceAccount#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhook
 */
export interface CloudnativePgWebhook {
  /**
   * @schema CloudnativePgWebhook#livenessProbe
   */
  readonly livenessProbe?: CloudnativePgWebhookLivenessProbe;

  /**
   * @schema CloudnativePgWebhook#mutating
   */
  readonly mutating?: CloudnativePgWebhookMutating;

  /**
   * @schema CloudnativePgWebhook#port
   */
  readonly port?: number;

  /**
   * @schema CloudnativePgWebhook#readinessProbe
   */
  readonly readinessProbe?: CloudnativePgWebhookReadinessProbe;

  /**
   * @schema CloudnativePgWebhook#startupProbe
   */
  readonly startupProbe?: CloudnativePgWebhookStartupProbe;

  /**
   * @schema CloudnativePgWebhook#validating
   */
  readonly validating?: CloudnativePgWebhookValidating;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhook#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgContainerSecurityContextCapabilities
 */
export interface CloudnativePgContainerSecurityContextCapabilities {
  /**
   * @schema CloudnativePgContainerSecurityContextCapabilities#drop
   */
  readonly drop?: string[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContextCapabilities#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgContainerSecurityContextSeccompProfile
 */
export interface CloudnativePgContainerSecurityContextSeccompProfile {
  /**
   * @schema CloudnativePgContainerSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgContainerSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgMonitoringGrafanaDashboard
 */
export interface CloudnativePgMonitoringGrafanaDashboard {
  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#annotations
   */
  readonly annotations?: any;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#configMapName
   */
  readonly configMapName?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#labels
   */
  readonly labels?: any;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#namespace
   */
  readonly namespace?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#sidecarLabel
   */
  readonly sidecarLabel?: string;

  /**
   * @schema CloudnativePgMonitoringGrafanaDashboard#sidecarLabelValue
   */
  readonly sidecarLabelValue?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgMonitoringGrafanaDashboard#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgPodSecurityContextSeccompProfile
 */
export interface CloudnativePgPodSecurityContextSeccompProfile {
  /**
   * @schema CloudnativePgPodSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgPodSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhookLivenessProbe
 */
export interface CloudnativePgWebhookLivenessProbe {
  /**
   * @schema CloudnativePgWebhookLivenessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookLivenessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhookMutating
 */
export interface CloudnativePgWebhookMutating {
  /**
   * @schema CloudnativePgWebhookMutating#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgWebhookMutating#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookMutating#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhookReadinessProbe
 */
export interface CloudnativePgWebhookReadinessProbe {
  /**
   * @schema CloudnativePgWebhookReadinessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhookStartupProbe
 */
export interface CloudnativePgWebhookStartupProbe {
  /**
   * @schema CloudnativePgWebhookStartupProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema CloudnativePgWebhookStartupProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookStartupProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema CloudnativePgWebhookValidating
 */
export interface CloudnativePgWebhookValidating {
  /**
   * @schema CloudnativePgWebhookValidating#create
   */
  readonly create?: boolean;

  /**
   * @schema CloudnativePgWebhookValidating#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema CloudnativePgWebhookValidating#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

