// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface ClusterProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: ClusterValues;
}

export class Cluster extends Construct {
  public constructor(scope: Construct, id: string, props: ClusterProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const { additionalValues, ...valuesWithoutAdditionalValues } = props.values;
      updatedProps = {
        ...props,
        values: {
          ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
          ...additionalValues,
        },
      };
    }

    const finalProps: HelmProps = {
      chart: 'cluster',
      repo: 'https://cloudnative-pg.github.io/charts',
      version: '0.3.1',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema cluster
 */
export interface ClusterValues {
  /**
   * @schema cluster#backups
   */
  readonly backups?: ClusterBackups;

  /**
   * @schema cluster#cluster
   */
  readonly cluster?: ClusterCluster;

  /**
   * @schema cluster#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema cluster#imageCatalog
   */
  readonly imageCatalog?: ClusterImageCatalog;

  /**
   * @schema cluster#mode
   */
  readonly mode?: string;

  /**
   * @schema cluster#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema cluster#namespaceOverride
   */
  readonly namespaceOverride?: string;

  /**
   * @schema cluster#poolers
   */
  readonly poolers?: any[];

  /**
   * @schema cluster#recovery
   */
  readonly recovery?: ClusterRecovery;

  /**
   * @schema cluster#type
   */
  readonly type?: string;

  /**
   * @schema cluster#version
   */
  readonly version?: ClusterVersion;

  /**
   * @schema cluster#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema cluster#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackups
 */
export interface ClusterBackups {
  /**
   * @schema ClusterBackups#azure
   */
  readonly azure?: ClusterBackupsAzure;

  /**
   * @schema ClusterBackups#data
   */
  readonly data?: ClusterBackupsData;

  /**
   * @schema ClusterBackups#destinationPath
   */
  readonly destinationPath?: string;

  /**
   * @schema ClusterBackups#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterBackups#endpointCA
   */
  readonly endpointCa?: ClusterBackupsEndpointCa;

  /**
   * @schema ClusterBackups#endpointURL
   */
  readonly endpointUrl?: string;

  /**
   * @schema ClusterBackups#google
   */
  readonly google?: ClusterBackupsGoogle;

  /**
   * @schema ClusterBackups#provider
   */
  readonly provider?: string;

  /**
   * @schema ClusterBackups#retentionPolicy
   */
  readonly retentionPolicy?: string;

  /**
   * @schema ClusterBackups#s3
   */
  readonly s3?: ClusterBackupsS3;

  /**
   * @schema ClusterBackups#scheduledBackups
   */
  readonly scheduledBackups?: ClusterBackupsScheduledBackups[];

  /**
   * @schema ClusterBackups#secret
   */
  readonly secret?: ClusterBackupsSecret;

  /**
   * @schema ClusterBackups#wal
   */
  readonly wal?: ClusterBackupsWal;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackups#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterCluster
 */
export interface ClusterCluster {
  /**
   * @schema ClusterCluster#additionalLabels
   */
  readonly additionalLabels?: any;

  /**
   * @schema ClusterCluster#affinity
   */
  readonly affinity?: ClusterClusterAffinity;

  /**
   * @schema ClusterCluster#annotations
   */
  readonly annotations?: any;

  /**
   * @schema ClusterCluster#certificates
   */
  readonly certificates?: any;

  /**
   * @schema ClusterCluster#enablePDB
   */
  readonly enablePdb?: boolean;

  /**
   * @schema ClusterCluster#enableSuperuserAccess
   */
  readonly enableSuperuserAccess?: boolean;

  /**
   * @schema ClusterCluster#imageCatalogRef
   */
  readonly imageCatalogRef?: any;

  /**
   * @schema ClusterCluster#imageName
   */
  readonly imageName?: string;

  /**
   * @schema ClusterCluster#imagePullPolicy
   */
  readonly imagePullPolicy?: string;

  /**
   * @schema ClusterCluster#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema ClusterCluster#initdb
   */
  readonly initdb?: any;

  /**
   * @schema ClusterCluster#instances
   */
  readonly instances?: number;

  /**
   * @schema ClusterCluster#logLevel
   */
  readonly logLevel?: string;

  /**
   * @schema ClusterCluster#monitoring
   */
  readonly monitoring?: ClusterClusterMonitoring;

  /**
   * @schema ClusterCluster#postgresGID
   */
  readonly postgresGid?: number;

  /**
   * @schema ClusterCluster#postgresUID
   */
  readonly postgresUid?: number;

  /**
   * @schema ClusterCluster#postgresql
   */
  readonly postgresql?: ClusterClusterPostgresql;

  /**
   * @schema ClusterCluster#primaryUpdateMethod
   */
  readonly primaryUpdateMethod?: string;

  /**
   * @schema ClusterCluster#primaryUpdateStrategy
   */
  readonly primaryUpdateStrategy?: string;

  /**
   * @schema ClusterCluster#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema ClusterCluster#resources
   */
  readonly resources?: any;

  /**
   * @schema ClusterCluster#roles
   */
  readonly roles?: any[];

  /**
   * @schema ClusterCluster#serviceAccountTemplate
   */
  readonly serviceAccountTemplate?: any;

  /**
   * @schema ClusterCluster#services
   */
  readonly services?: any;

  /**
   * @schema ClusterCluster#storage
   */
  readonly storage?: ClusterClusterStorage;

  /**
   * @schema ClusterCluster#superuserSecret
   */
  readonly superuserSecret?: string;

  /**
   * @schema ClusterCluster#walStorage
   */
  readonly walStorage?: ClusterClusterWalStorage;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterCluster#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterImageCatalog
 */
export interface ClusterImageCatalog {
  /**
   * @schema ClusterImageCatalog#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterImageCatalog#images
   */
  readonly images?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterImageCatalog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecovery
 */
export interface ClusterRecovery {
  /**
   * @schema ClusterRecovery#azure
   */
  readonly azure?: ClusterRecoveryAzure;

  /**
   * @schema ClusterRecovery#backupName
   */
  readonly backupName?: string;

  /**
   * @schema ClusterRecovery#clusterName
   */
  readonly clusterName?: string;

  /**
   * @schema ClusterRecovery#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecovery#destinationPath
   */
  readonly destinationPath?: string;

  /**
   * @schema ClusterRecovery#endpointCA
   */
  readonly endpointCa?: ClusterRecoveryEndpointCa;

  /**
   * @schema ClusterRecovery#endpointURL
   */
  readonly endpointUrl?: string;

  /**
   * @schema ClusterRecovery#google
   */
  readonly google?: ClusterRecoveryGoogle;

  /**
   * @schema ClusterRecovery#import
   */
  readonly import?: ClusterRecoveryImport;

  /**
   * @schema ClusterRecovery#method
   */
  readonly method?: string;

  /**
   * @schema ClusterRecovery#owner
   */
  readonly owner?: string;

  /**
   * @schema ClusterRecovery#pgBaseBackup
   */
  readonly pgBaseBackup?: ClusterRecoveryPgBaseBackup;

  /**
   * @schema ClusterRecovery#pitrTarget
   */
  readonly pitrTarget?: ClusterRecoveryPitrTarget;

  /**
   * @schema ClusterRecovery#provider
   */
  readonly provider?: string;

  /**
   * @schema ClusterRecovery#s3
   */
  readonly s3?: ClusterRecoveryS3;

  /**
   * @schema ClusterRecovery#secret
   */
  readonly secret?: ClusterRecoverySecret;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecovery#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterVersion
 */
export interface ClusterVersion {
  /**
   * @schema ClusterVersion#postgis
   */
  readonly postgis?: string;

  /**
   * @schema ClusterVersion#postgresql
   */
  readonly postgresql?: string;

  /**
   * @schema ClusterVersion#timescaledb
   */
  readonly timescaledb?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterVersion#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsAzure
 */
export interface ClusterBackupsAzure {
  /**
   * @schema ClusterBackupsAzure#connectionString
   */
  readonly connectionString?: string;

  /**
   * @schema ClusterBackupsAzure#containerName
   */
  readonly containerName?: string;

  /**
   * @schema ClusterBackupsAzure#inheritFromAzureAD
   */
  readonly inheritFromAzureAd?: boolean;

  /**
   * @schema ClusterBackupsAzure#path
   */
  readonly path?: string;

  /**
   * @schema ClusterBackupsAzure#serviceName
   */
  readonly serviceName?: string;

  /**
   * @schema ClusterBackupsAzure#storageAccount
   */
  readonly storageAccount?: string;

  /**
   * @schema ClusterBackupsAzure#storageKey
   */
  readonly storageKey?: string;

  /**
   * @schema ClusterBackupsAzure#storageSasToken
   */
  readonly storageSasToken?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsAzure#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsData
 */
export interface ClusterBackupsData {
  /**
   * @schema ClusterBackupsData#compression
   */
  readonly compression?: string;

  /**
   * @schema ClusterBackupsData#encryption
   */
  readonly encryption?: string;

  /**
   * @schema ClusterBackupsData#jobs
   */
  readonly jobs?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsData#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsEndpointCa
 */
export interface ClusterBackupsEndpointCa {
  /**
   * @schema ClusterBackupsEndpointCa#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterBackupsEndpointCa#key
   */
  readonly key?: string;

  /**
   * @schema ClusterBackupsEndpointCa#name
   */
  readonly name?: string;

  /**
   * @schema ClusterBackupsEndpointCa#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsEndpointCa#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsGoogle
 */
export interface ClusterBackupsGoogle {
  /**
   * @schema ClusterBackupsGoogle#applicationCredentials
   */
  readonly applicationCredentials?: string;

  /**
   * @schema ClusterBackupsGoogle#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterBackupsGoogle#gkeEnvironment
   */
  readonly gkeEnvironment?: boolean;

  /**
   * @schema ClusterBackupsGoogle#path
   */
  readonly path?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsGoogle#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsS3
 */
export interface ClusterBackupsS3 {
  /**
   * @schema ClusterBackupsS3#accessKey
   */
  readonly accessKey?: string;

  /**
   * @schema ClusterBackupsS3#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterBackupsS3#inheritFromIAMRole
   */
  readonly inheritFromIamRole?: boolean;

  /**
   * @schema ClusterBackupsS3#path
   */
  readonly path?: string;

  /**
   * @schema ClusterBackupsS3#region
   */
  readonly region?: string;

  /**
   * @schema ClusterBackupsS3#secretKey
   */
  readonly secretKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsS3#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsScheduledBackups
 */
export interface ClusterBackupsScheduledBackups {
  /**
   * @schema ClusterBackupsScheduledBackups#backupOwnerReference
   */
  readonly backupOwnerReference?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#method
   */
  readonly method?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#name
   */
  readonly name?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#schedule
   */
  readonly schedule?: string;

}

/**
 * @schema ClusterBackupsSecret
 */
export interface ClusterBackupsSecret {
  /**
   * @schema ClusterBackupsSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterBackupsSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterBackupsWal
 */
export interface ClusterBackupsWal {
  /**
   * @schema ClusterBackupsWal#compression
   */
  readonly compression?: string;

  /**
   * @schema ClusterBackupsWal#encryption
   */
  readonly encryption?: string;

  /**
   * @schema ClusterBackupsWal#maxParallel
   */
  readonly maxParallel?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsWal#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterAffinity
 */
export interface ClusterClusterAffinity {
  /**
   * @schema ClusterClusterAffinity#topologyKey
   */
  readonly topologyKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterAffinity#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterMonitoring
 */
export interface ClusterClusterMonitoring {
  /**
   * @schema ClusterClusterMonitoring#customQueries
   */
  readonly customQueries?: any[];

  /**
   * @schema ClusterClusterMonitoring#customQueriesSecret
   */
  readonly customQueriesSecret?: any[];

  /**
   * @schema ClusterClusterMonitoring#disableDefaultQueries
   */
  readonly disableDefaultQueries?: boolean;

  /**
   * @schema ClusterClusterMonitoring#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoring#podMonitor
   */
  readonly podMonitor?: ClusterClusterMonitoringPodMonitor;

  /**
   * @schema ClusterClusterMonitoring#prometheusRule
   */
  readonly prometheusRule?: ClusterClusterMonitoringPrometheusRule;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoring#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterPostgresql
 */
export interface ClusterClusterPostgresql {
  /**
   * @schema ClusterClusterPostgresql#ldap
   */
  readonly ldap?: any;

  /**
   * @schema ClusterClusterPostgresql#parameters
   */
  readonly parameters?: any;

  /**
   * @schema ClusterClusterPostgresql#pg_hba
   */
  readonly pgHba?: any[];

  /**
   * @schema ClusterClusterPostgresql#pg_ident
   */
  readonly pgIdent?: any[];

  /**
   * @schema ClusterClusterPostgresql#shared_preload_libraries
   */
  readonly sharedPreloadLibraries?: any[];

  /**
   * @schema ClusterClusterPostgresql#synchronous
   */
  readonly synchronous?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterPostgresql#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterStorage
 */
export interface ClusterClusterStorage {
  /**
   * @schema ClusterClusterStorage#size
   */
  readonly size?: string;

  /**
   * @schema ClusterClusterStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterWalStorage
 */
export interface ClusterClusterWalStorage {
  /**
   * @schema ClusterClusterWalStorage#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterWalStorage#size
   */
  readonly size?: string;

  /**
   * @schema ClusterClusterWalStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterWalStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryAzure
 */
export interface ClusterRecoveryAzure {
  /**
   * @schema ClusterRecoveryAzure#connectionString
   */
  readonly connectionString?: string;

  /**
   * @schema ClusterRecoveryAzure#containerName
   */
  readonly containerName?: string;

  /**
   * @schema ClusterRecoveryAzure#inheritFromAzureAD
   */
  readonly inheritFromAzureAd?: boolean;

  /**
   * @schema ClusterRecoveryAzure#path
   */
  readonly path?: string;

  /**
   * @schema ClusterRecoveryAzure#serviceName
   */
  readonly serviceName?: string;

  /**
   * @schema ClusterRecoveryAzure#storageAccount
   */
  readonly storageAccount?: string;

  /**
   * @schema ClusterRecoveryAzure#storageKey
   */
  readonly storageKey?: string;

  /**
   * @schema ClusterRecoveryAzure#storageSasToken
   */
  readonly storageSasToken?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryAzure#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryEndpointCa
 */
export interface ClusterRecoveryEndpointCa {
  /**
   * @schema ClusterRecoveryEndpointCa#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryEndpointCa#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryEndpointCa#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryEndpointCa#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryEndpointCa#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryGoogle
 */
export interface ClusterRecoveryGoogle {
  /**
   * @schema ClusterRecoveryGoogle#applicationCredentials
   */
  readonly applicationCredentials?: string;

  /**
   * @schema ClusterRecoveryGoogle#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterRecoveryGoogle#gkeEnvironment
   */
  readonly gkeEnvironment?: boolean;

  /**
   * @schema ClusterRecoveryGoogle#path
   */
  readonly path?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryGoogle#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImport
 */
export interface ClusterRecoveryImport {
  /**
   * @schema ClusterRecoveryImport#databases
   */
  readonly databases?: any[];

  /**
   * @schema ClusterRecoveryImport#pgDumpExtraOptions
   */
  readonly pgDumpExtraOptions?: any[];

  /**
   * @schema ClusterRecoveryImport#pgRestoreExtraOptions
   */
  readonly pgRestoreExtraOptions?: any[];

  /**
   * @schema ClusterRecoveryImport#postImportApplicationSQL
   */
  readonly postImportApplicationSql?: any[];

  /**
   * @schema ClusterRecoveryImport#roles
   */
  readonly roles?: any[];

  /**
   * @schema ClusterRecoveryImport#schemaOnly
   */
  readonly schemaOnly?: boolean;

  /**
   * @schema ClusterRecoveryImport#source
   */
  readonly source?: ClusterRecoveryImportSource;

  /**
   * @schema ClusterRecoveryImport#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImport#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackup
 */
export interface ClusterRecoveryPgBaseBackup {
  /**
   * @schema ClusterRecoveryPgBaseBackup#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#owner
   */
  readonly owner?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#secret
   */
  readonly secret?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#source
   */
  readonly source?: ClusterRecoveryPgBaseBackupSource;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackup#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPitrTarget
 */
export interface ClusterRecoveryPitrTarget {
  /**
   * @schema ClusterRecoveryPitrTarget#time
   */
  readonly time?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPitrTarget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryS3
 */
export interface ClusterRecoveryS3 {
  /**
   * @schema ClusterRecoveryS3#accessKey
   */
  readonly accessKey?: string;

  /**
   * @schema ClusterRecoveryS3#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterRecoveryS3#inheritFromIAMRole
   */
  readonly inheritFromIamRole?: boolean;

  /**
   * @schema ClusterRecoveryS3#path
   */
  readonly path?: string;

  /**
   * @schema ClusterRecoveryS3#region
   */
  readonly region?: string;

  /**
   * @schema ClusterRecoveryS3#secretKey
   */
  readonly secretKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryS3#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoverySecret
 */
export interface ClusterRecoverySecret {
  /**
   * @schema ClusterRecoverySecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoverySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoverySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterMonitoringPodMonitor
 */
export interface ClusterClusterMonitoringPodMonitor {
  /**
   * @schema ClusterClusterMonitoringPodMonitor#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoringPodMonitor#metricRelabelings
   */
  readonly metricRelabelings?: any[];

  /**
   * @schema ClusterClusterMonitoringPodMonitor#relabelings
   */
  readonly relabelings?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoringPodMonitor#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterClusterMonitoringPrometheusRule
 */
export interface ClusterClusterMonitoringPrometheusRule {
  /**
   * @schema ClusterClusterMonitoringPrometheusRule#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoringPrometheusRule#excludeRules
   */
  readonly excludeRules?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoringPrometheusRule#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImportSource
 */
export interface ClusterRecoveryImportSource {
  /**
   * @schema ClusterRecoveryImportSource#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryImportSource#host
   */
  readonly host?: string;

  /**
   * @schema ClusterRecoveryImportSource#passwordSecret
   */
  readonly passwordSecret?: ClusterRecoveryImportSourcePasswordSecret;

  /**
   * @schema ClusterRecoveryImportSource#port
   */
  readonly port?: number;

  /**
   * @schema ClusterRecoveryImportSource#sslCertSecret
   */
  readonly sslCertSecret?: ClusterRecoveryImportSourceSslCertSecret;

  /**
   * @schema ClusterRecoveryImportSource#sslKeySecret
   */
  readonly sslKeySecret?: ClusterRecoveryImportSourceSslKeySecret;

  /**
   * @schema ClusterRecoveryImportSource#sslMode
   */
  readonly sslMode?: string;

  /**
   * @schema ClusterRecoveryImportSource#sslRootCertSecret
   */
  readonly sslRootCertSecret?: ClusterRecoveryImportSourceSslRootCertSecret;

  /**
   * @schema ClusterRecoveryImportSource#username
   */
  readonly username?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSource#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackupSource
 */
export interface ClusterRecoveryPgBaseBackupSource {
  /**
   * @schema ClusterRecoveryPgBaseBackupSource#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#host
   */
  readonly host?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#passwordSecret
   */
  readonly passwordSecret?: ClusterRecoveryPgBaseBackupSourcePasswordSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#port
   */
  readonly port?: number;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslCertSecret
   */
  readonly sslCertSecret?: ClusterRecoveryPgBaseBackupSourceSslCertSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslKeySecret
   */
  readonly sslKeySecret?: ClusterRecoveryPgBaseBackupSourceSslKeySecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslMode
   */
  readonly sslMode?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslRootCertSecret
   */
  readonly sslRootCertSecret?: ClusterRecoveryPgBaseBackupSourceSslRootCertSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#username
   */
  readonly username?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSource#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImportSourcePasswordSecret
 */
export interface ClusterRecoveryImportSourcePasswordSecret {
  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourcePasswordSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImportSourceSslCertSecret
 */
export interface ClusterRecoveryImportSourceSslCertSecret {
  /**
   * @schema ClusterRecoveryImportSourceSslCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImportSourceSslKeySecret
 */
export interface ClusterRecoveryImportSourceSslKeySecret {
  /**
   * @schema ClusterRecoveryImportSourceSslKeySecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslKeySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslKeySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryImportSourceSslRootCertSecret
 */
export interface ClusterRecoveryImportSourceSslRootCertSecret {
  /**
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret
 */
export interface ClusterRecoveryPgBaseBackupSourcePasswordSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslCertSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslKeySecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslRootCertSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

