// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface ClusterProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: ClusterValues;
}

export class Cluster extends Construct {
  public constructor(scope: Construct, id: string, props: ClusterProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_ClusterValues(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'cluster',
      repo: 'https://cloudnative-pg.github.io/charts',
      version: '0.3.1',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema cluster
 */
export interface ClusterValues {
  /**
   * @schema cluster#backups
   */
  readonly backups?: ClusterBackups;

  /**
   * @schema cluster#cluster
   */
  readonly cluster?: ClusterCluster;

  /**
   * @schema cluster#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema cluster#imageCatalog
   */
  readonly imageCatalog?: ClusterImageCatalog;

  /**
   * @schema cluster#mode
   */
  readonly mode?: string;

  /**
   * @schema cluster#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema cluster#namespaceOverride
   */
  readonly namespaceOverride?: string;

  /**
   * @schema cluster#poolers
   */
  readonly poolers?: any[];

  /**
   * @schema cluster#recovery
   */
  readonly recovery?: ClusterRecovery;

  /**
   * @schema cluster#type
   */
  readonly type?: string;

  /**
   * @schema cluster#version
   */
  readonly version?: ClusterVersion;

  /**
   * @schema cluster#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema cluster#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterValues' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterValues(obj: ClusterValues | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'backups': toJson_ClusterBackups(obj.backups),
    'cluster': toJson_ClusterCluster(obj.cluster),
    'fullnameOverride': obj.fullnameOverride,
    'imageCatalog': toJson_ClusterImageCatalog(obj.imageCatalog),
    'mode': obj.mode,
    'nameOverride': obj.nameOverride,
    'namespaceOverride': obj.namespaceOverride,
    'poolers': obj.poolers?.map(y => y),
    'recovery': toJson_ClusterRecovery(obj.recovery),
    'type': obj.type,
    'version': toJson_ClusterVersion(obj.version),
    'global': ((obj.global) === undefined) ? undefined : (Object.entries(obj.global).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackups
 */
export interface ClusterBackups {
  /**
   * @schema ClusterBackups#azure
   */
  readonly azure?: ClusterBackupsAzure;

  /**
   * @schema ClusterBackups#data
   */
  readonly data?: ClusterBackupsData;

  /**
   * @schema ClusterBackups#destinationPath
   */
  readonly destinationPath?: string;

  /**
   * @schema ClusterBackups#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterBackups#endpointCA
   */
  readonly endpointCa?: ClusterBackupsEndpointCa;

  /**
   * @schema ClusterBackups#endpointURL
   */
  readonly endpointUrl?: string;

  /**
   * @schema ClusterBackups#google
   */
  readonly google?: ClusterBackupsGoogle;

  /**
   * @schema ClusterBackups#provider
   */
  readonly provider?: string;

  /**
   * @schema ClusterBackups#retentionPolicy
   */
  readonly retentionPolicy?: string;

  /**
   * @schema ClusterBackups#s3
   */
  readonly s3?: ClusterBackupsS3;

  /**
   * @schema ClusterBackups#scheduledBackups
   */
  readonly scheduledBackups?: ClusterBackupsScheduledBackups[];

  /**
   * @schema ClusterBackups#secret
   */
  readonly secret?: ClusterBackupsSecret;

  /**
   * @schema ClusterBackups#wal
   */
  readonly wal?: ClusterBackupsWal;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackups#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackups' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackups(obj: ClusterBackups | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'azure': toJson_ClusterBackupsAzure(obj.azure),
    'data': toJson_ClusterBackupsData(obj.data),
    'destinationPath': obj.destinationPath,
    'enabled': obj.enabled,
    'endpointCA': toJson_ClusterBackupsEndpointCa(obj.endpointCa),
    'endpointURL': obj.endpointUrl,
    'google': toJson_ClusterBackupsGoogle(obj.google),
    'provider': obj.provider,
    'retentionPolicy': obj.retentionPolicy,
    's3': toJson_ClusterBackupsS3(obj.s3),
    'scheduledBackups': obj.scheduledBackups?.map(y => toJson_ClusterBackupsScheduledBackups(y)),
    'secret': toJson_ClusterBackupsSecret(obj.secret),
    'wal': toJson_ClusterBackupsWal(obj.wal),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterCluster
 */
export interface ClusterCluster {
  /**
   * @schema ClusterCluster#additionalLabels
   */
  readonly additionalLabels?: any;

  /**
   * @schema ClusterCluster#affinity
   */
  readonly affinity?: ClusterClusterAffinity;

  /**
   * @schema ClusterCluster#annotations
   */
  readonly annotations?: any;

  /**
   * @schema ClusterCluster#certificates
   */
  readonly certificates?: any;

  /**
   * @schema ClusterCluster#enablePDB
   */
  readonly enablePdb?: boolean;

  /**
   * @schema ClusterCluster#enableSuperuserAccess
   */
  readonly enableSuperuserAccess?: boolean;

  /**
   * @schema ClusterCluster#imageCatalogRef
   */
  readonly imageCatalogRef?: any;

  /**
   * @schema ClusterCluster#imageName
   */
  readonly imageName?: string;

  /**
   * @schema ClusterCluster#imagePullPolicy
   */
  readonly imagePullPolicy?: string;

  /**
   * @schema ClusterCluster#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema ClusterCluster#initdb
   */
  readonly initdb?: any;

  /**
   * @schema ClusterCluster#instances
   */
  readonly instances?: number;

  /**
   * @schema ClusterCluster#logLevel
   */
  readonly logLevel?: string;

  /**
   * @schema ClusterCluster#monitoring
   */
  readonly monitoring?: ClusterClusterMonitoring;

  /**
   * @schema ClusterCluster#postgresGID
   */
  readonly postgresGid?: number;

  /**
   * @schema ClusterCluster#postgresUID
   */
  readonly postgresUid?: number;

  /**
   * @schema ClusterCluster#postgresql
   */
  readonly postgresql?: ClusterClusterPostgresql;

  /**
   * @schema ClusterCluster#primaryUpdateMethod
   */
  readonly primaryUpdateMethod?: string;

  /**
   * @schema ClusterCluster#primaryUpdateStrategy
   */
  readonly primaryUpdateStrategy?: string;

  /**
   * @schema ClusterCluster#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema ClusterCluster#resources
   */
  readonly resources?: any;

  /**
   * @schema ClusterCluster#roles
   */
  readonly roles?: any[];

  /**
   * @schema ClusterCluster#serviceAccountTemplate
   */
  readonly serviceAccountTemplate?: any;

  /**
   * @schema ClusterCluster#services
   */
  readonly services?: any;

  /**
   * @schema ClusterCluster#storage
   */
  readonly storage?: ClusterClusterStorage;

  /**
   * @schema ClusterCluster#superuserSecret
   */
  readonly superuserSecret?: string;

  /**
   * @schema ClusterCluster#walStorage
   */
  readonly walStorage?: ClusterClusterWalStorage;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterCluster#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterCluster' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCluster(obj: ClusterCluster | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'additionalLabels': obj.additionalLabels,
    'affinity': toJson_ClusterClusterAffinity(obj.affinity),
    'annotations': obj.annotations,
    'certificates': obj.certificates,
    'enablePDB': obj.enablePdb,
    'enableSuperuserAccess': obj.enableSuperuserAccess,
    'imageCatalogRef': obj.imageCatalogRef,
    'imageName': obj.imageName,
    'imagePullPolicy': obj.imagePullPolicy,
    'imagePullSecrets': obj.imagePullSecrets?.map(y => y),
    'initdb': obj.initdb,
    'instances': obj.instances,
    'logLevel': obj.logLevel,
    'monitoring': toJson_ClusterClusterMonitoring(obj.monitoring),
    'postgresGID': obj.postgresGid,
    'postgresUID': obj.postgresUid,
    'postgresql': toJson_ClusterClusterPostgresql(obj.postgresql),
    'primaryUpdateMethod': obj.primaryUpdateMethod,
    'primaryUpdateStrategy': obj.primaryUpdateStrategy,
    'priorityClassName': obj.priorityClassName,
    'resources': obj.resources,
    'roles': obj.roles?.map(y => y),
    'serviceAccountTemplate': obj.serviceAccountTemplate,
    'services': obj.services,
    'storage': toJson_ClusterClusterStorage(obj.storage),
    'superuserSecret': obj.superuserSecret,
    'walStorage': toJson_ClusterClusterWalStorage(obj.walStorage),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterImageCatalog
 */
export interface ClusterImageCatalog {
  /**
   * @schema ClusterImageCatalog#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterImageCatalog#images
   */
  readonly images?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterImageCatalog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterImageCatalog' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterImageCatalog(obj: ClusterImageCatalog | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'images': obj.images?.map(y => y),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecovery
 */
export interface ClusterRecovery {
  /**
   * @schema ClusterRecovery#azure
   */
  readonly azure?: ClusterRecoveryAzure;

  /**
   * @schema ClusterRecovery#backupName
   */
  readonly backupName?: string;

  /**
   * @schema ClusterRecovery#clusterName
   */
  readonly clusterName?: string;

  /**
   * @schema ClusterRecovery#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecovery#destinationPath
   */
  readonly destinationPath?: string;

  /**
   * @schema ClusterRecovery#endpointCA
   */
  readonly endpointCa?: ClusterRecoveryEndpointCa;

  /**
   * @schema ClusterRecovery#endpointURL
   */
  readonly endpointUrl?: string;

  /**
   * @schema ClusterRecovery#google
   */
  readonly google?: ClusterRecoveryGoogle;

  /**
   * @schema ClusterRecovery#import
   */
  readonly import?: ClusterRecoveryImport;

  /**
   * @schema ClusterRecovery#method
   */
  readonly method?: string;

  /**
   * @schema ClusterRecovery#owner
   */
  readonly owner?: string;

  /**
   * @schema ClusterRecovery#pgBaseBackup
   */
  readonly pgBaseBackup?: ClusterRecoveryPgBaseBackup;

  /**
   * @schema ClusterRecovery#pitrTarget
   */
  readonly pitrTarget?: ClusterRecoveryPitrTarget;

  /**
   * @schema ClusterRecovery#provider
   */
  readonly provider?: string;

  /**
   * @schema ClusterRecovery#s3
   */
  readonly s3?: ClusterRecoveryS3;

  /**
   * @schema ClusterRecovery#secret
   */
  readonly secret?: ClusterRecoverySecret;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecovery#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecovery' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecovery(obj: ClusterRecovery | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'azure': toJson_ClusterRecoveryAzure(obj.azure),
    'backupName': obj.backupName,
    'clusterName': obj.clusterName,
    'database': obj.database,
    'destinationPath': obj.destinationPath,
    'endpointCA': toJson_ClusterRecoveryEndpointCa(obj.endpointCa),
    'endpointURL': obj.endpointUrl,
    'google': toJson_ClusterRecoveryGoogle(obj.google),
    'import': toJson_ClusterRecoveryImport(obj.import),
    'method': obj.method,
    'owner': obj.owner,
    'pgBaseBackup': toJson_ClusterRecoveryPgBaseBackup(obj.pgBaseBackup),
    'pitrTarget': toJson_ClusterRecoveryPitrTarget(obj.pitrTarget),
    'provider': obj.provider,
    's3': toJson_ClusterRecoveryS3(obj.s3),
    'secret': toJson_ClusterRecoverySecret(obj.secret),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterVersion
 */
export interface ClusterVersion {
  /**
   * @schema ClusterVersion#postgis
   */
  readonly postgis?: string;

  /**
   * @schema ClusterVersion#postgresql
   */
  readonly postgresql?: string;

  /**
   * @schema ClusterVersion#timescaledb
   */
  readonly timescaledb?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterVersion#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterVersion' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterVersion(obj: ClusterVersion | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'postgis': obj.postgis,
    'postgresql': obj.postgresql,
    'timescaledb': obj.timescaledb,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsAzure
 */
export interface ClusterBackupsAzure {
  /**
   * @schema ClusterBackupsAzure#connectionString
   */
  readonly connectionString?: string;

  /**
   * @schema ClusterBackupsAzure#containerName
   */
  readonly containerName?: string;

  /**
   * @schema ClusterBackupsAzure#inheritFromAzureAD
   */
  readonly inheritFromAzureAd?: boolean;

  /**
   * @schema ClusterBackupsAzure#path
   */
  readonly path?: string;

  /**
   * @schema ClusterBackupsAzure#serviceName
   */
  readonly serviceName?: string;

  /**
   * @schema ClusterBackupsAzure#storageAccount
   */
  readonly storageAccount?: string;

  /**
   * @schema ClusterBackupsAzure#storageKey
   */
  readonly storageKey?: string;

  /**
   * @schema ClusterBackupsAzure#storageSasToken
   */
  readonly storageSasToken?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsAzure#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsAzure' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsAzure(obj: ClusterBackupsAzure | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'connectionString': obj.connectionString,
    'containerName': obj.containerName,
    'inheritFromAzureAD': obj.inheritFromAzureAd,
    'path': obj.path,
    'serviceName': obj.serviceName,
    'storageAccount': obj.storageAccount,
    'storageKey': obj.storageKey,
    'storageSasToken': obj.storageSasToken,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsData
 */
export interface ClusterBackupsData {
  /**
   * @schema ClusterBackupsData#compression
   */
  readonly compression?: string;

  /**
   * @schema ClusterBackupsData#encryption
   */
  readonly encryption?: string;

  /**
   * @schema ClusterBackupsData#jobs
   */
  readonly jobs?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsData#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsData' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsData(obj: ClusterBackupsData | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'compression': obj.compression,
    'encryption': obj.encryption,
    'jobs': obj.jobs,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsEndpointCa
 */
export interface ClusterBackupsEndpointCa {
  /**
   * @schema ClusterBackupsEndpointCa#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterBackupsEndpointCa#key
   */
  readonly key?: string;

  /**
   * @schema ClusterBackupsEndpointCa#name
   */
  readonly name?: string;

  /**
   * @schema ClusterBackupsEndpointCa#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsEndpointCa#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsEndpointCa' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsEndpointCa(obj: ClusterBackupsEndpointCa | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'key': obj.key,
    'name': obj.name,
    'value': obj.value,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsGoogle
 */
export interface ClusterBackupsGoogle {
  /**
   * @schema ClusterBackupsGoogle#applicationCredentials
   */
  readonly applicationCredentials?: string;

  /**
   * @schema ClusterBackupsGoogle#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterBackupsGoogle#gkeEnvironment
   */
  readonly gkeEnvironment?: boolean;

  /**
   * @schema ClusterBackupsGoogle#path
   */
  readonly path?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsGoogle#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsGoogle' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsGoogle(obj: ClusterBackupsGoogle | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'applicationCredentials': obj.applicationCredentials,
    'bucket': obj.bucket,
    'gkeEnvironment': obj.gkeEnvironment,
    'path': obj.path,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsS3
 */
export interface ClusterBackupsS3 {
  /**
   * @schema ClusterBackupsS3#accessKey
   */
  readonly accessKey?: string;

  /**
   * @schema ClusterBackupsS3#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterBackupsS3#inheritFromIAMRole
   */
  readonly inheritFromIamRole?: boolean;

  /**
   * @schema ClusterBackupsS3#path
   */
  readonly path?: string;

  /**
   * @schema ClusterBackupsS3#region
   */
  readonly region?: string;

  /**
   * @schema ClusterBackupsS3#secretKey
   */
  readonly secretKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsS3#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsS3' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsS3(obj: ClusterBackupsS3 | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKey': obj.accessKey,
    'bucket': obj.bucket,
    'inheritFromIAMRole': obj.inheritFromIamRole,
    'path': obj.path,
    'region': obj.region,
    'secretKey': obj.secretKey,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsScheduledBackups
 */
export interface ClusterBackupsScheduledBackups {
  /**
   * @schema ClusterBackupsScheduledBackups#backupOwnerReference
   */
  readonly backupOwnerReference?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#method
   */
  readonly method?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#name
   */
  readonly name?: string;

  /**
   * @schema ClusterBackupsScheduledBackups#schedule
   */
  readonly schedule?: string;
}

/**
 * Converts an object of type 'ClusterBackupsScheduledBackups' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsScheduledBackups(obj: ClusterBackupsScheduledBackups | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'backupOwnerReference': obj.backupOwnerReference,
    'method': obj.method,
    'name': obj.name,
    'schedule': obj.schedule,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsSecret
 */
export interface ClusterBackupsSecret {
  /**
   * @schema ClusterBackupsSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterBackupsSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsSecret(obj: ClusterBackupsSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterBackupsWal
 */
export interface ClusterBackupsWal {
  /**
   * @schema ClusterBackupsWal#compression
   */
  readonly compression?: string;

  /**
   * @schema ClusterBackupsWal#encryption
   */
  readonly encryption?: string;

  /**
   * @schema ClusterBackupsWal#maxParallel
   */
  readonly maxParallel?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterBackupsWal#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterBackupsWal' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterBackupsWal(obj: ClusterBackupsWal | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'compression': obj.compression,
    'encryption': obj.encryption,
    'maxParallel': obj.maxParallel,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterAffinity
 */
export interface ClusterClusterAffinity {
  /**
   * @schema ClusterClusterAffinity#topologyKey
   */
  readonly topologyKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterAffinity#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterAffinity' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterAffinity(obj: ClusterClusterAffinity | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'topologyKey': obj.topologyKey,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterMonitoring
 */
export interface ClusterClusterMonitoring {
  /**
   * @schema ClusterClusterMonitoring#customQueries
   */
  readonly customQueries?: any[];

  /**
   * @schema ClusterClusterMonitoring#customQueriesSecret
   */
  readonly customQueriesSecret?: any[];

  /**
   * @schema ClusterClusterMonitoring#disableDefaultQueries
   */
  readonly disableDefaultQueries?: boolean;

  /**
   * @schema ClusterClusterMonitoring#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoring#podMonitor
   */
  readonly podMonitor?: ClusterClusterMonitoringPodMonitor;

  /**
   * @schema ClusterClusterMonitoring#prometheusRule
   */
  readonly prometheusRule?: ClusterClusterMonitoringPrometheusRule;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoring#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterMonitoring' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterMonitoring(obj: ClusterClusterMonitoring | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'customQueries': obj.customQueries?.map(y => y),
    'customQueriesSecret': obj.customQueriesSecret?.map(y => y),
    'disableDefaultQueries': obj.disableDefaultQueries,
    'enabled': obj.enabled,
    'podMonitor': toJson_ClusterClusterMonitoringPodMonitor(obj.podMonitor),
    'prometheusRule': toJson_ClusterClusterMonitoringPrometheusRule(obj.prometheusRule),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterPostgresql
 */
export interface ClusterClusterPostgresql {
  /**
   * @schema ClusterClusterPostgresql#ldap
   */
  readonly ldap?: any;

  /**
   * @schema ClusterClusterPostgresql#parameters
   */
  readonly parameters?: any;

  /**
   * @schema ClusterClusterPostgresql#pg_hba
   */
  readonly pgHba?: any[];

  /**
   * @schema ClusterClusterPostgresql#pg_ident
   */
  readonly pgIdent?: any[];

  /**
   * @schema ClusterClusterPostgresql#shared_preload_libraries
   */
  readonly sharedPreloadLibraries?: any[];

  /**
   * @schema ClusterClusterPostgresql#synchronous
   */
  readonly synchronous?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterPostgresql#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterPostgresql' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterPostgresql(obj: ClusterClusterPostgresql | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ldap': obj.ldap,
    'parameters': obj.parameters,
    'pg_hba': obj.pgHba?.map(y => y),
    'pg_ident': obj.pgIdent?.map(y => y),
    'shared_preload_libraries': obj.sharedPreloadLibraries?.map(y => y),
    'synchronous': obj.synchronous,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterStorage
 */
export interface ClusterClusterStorage {
  /**
   * @schema ClusterClusterStorage#size
   */
  readonly size?: string;

  /**
   * @schema ClusterClusterStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterStorage' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterStorage(obj: ClusterClusterStorage | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'size': obj.size,
    'storageClass': obj.storageClass,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterWalStorage
 */
export interface ClusterClusterWalStorage {
  /**
   * @schema ClusterClusterWalStorage#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterWalStorage#size
   */
  readonly size?: string;

  /**
   * @schema ClusterClusterWalStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterWalStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterWalStorage' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterWalStorage(obj: ClusterClusterWalStorage | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enabled': obj.enabled,
    'size': obj.size,
    'storageClass': obj.storageClass,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryAzure
 */
export interface ClusterRecoveryAzure {
  /**
   * @schema ClusterRecoveryAzure#connectionString
   */
  readonly connectionString?: string;

  /**
   * @schema ClusterRecoveryAzure#containerName
   */
  readonly containerName?: string;

  /**
   * @schema ClusterRecoveryAzure#inheritFromAzureAD
   */
  readonly inheritFromAzureAd?: boolean;

  /**
   * @schema ClusterRecoveryAzure#path
   */
  readonly path?: string;

  /**
   * @schema ClusterRecoveryAzure#serviceName
   */
  readonly serviceName?: string;

  /**
   * @schema ClusterRecoveryAzure#storageAccount
   */
  readonly storageAccount?: string;

  /**
   * @schema ClusterRecoveryAzure#storageKey
   */
  readonly storageKey?: string;

  /**
   * @schema ClusterRecoveryAzure#storageSasToken
   */
  readonly storageSasToken?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryAzure#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryAzure' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryAzure(obj: ClusterRecoveryAzure | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'connectionString': obj.connectionString,
    'containerName': obj.containerName,
    'inheritFromAzureAD': obj.inheritFromAzureAd,
    'path': obj.path,
    'serviceName': obj.serviceName,
    'storageAccount': obj.storageAccount,
    'storageKey': obj.storageKey,
    'storageSasToken': obj.storageSasToken,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryEndpointCa
 */
export interface ClusterRecoveryEndpointCa {
  /**
   * @schema ClusterRecoveryEndpointCa#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryEndpointCa#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryEndpointCa#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryEndpointCa#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryEndpointCa#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryEndpointCa' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryEndpointCa(obj: ClusterRecoveryEndpointCa | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'key': obj.key,
    'name': obj.name,
    'value': obj.value,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryGoogle
 */
export interface ClusterRecoveryGoogle {
  /**
   * @schema ClusterRecoveryGoogle#applicationCredentials
   */
  readonly applicationCredentials?: string;

  /**
   * @schema ClusterRecoveryGoogle#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterRecoveryGoogle#gkeEnvironment
   */
  readonly gkeEnvironment?: boolean;

  /**
   * @schema ClusterRecoveryGoogle#path
   */
  readonly path?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryGoogle#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryGoogle' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryGoogle(obj: ClusterRecoveryGoogle | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'applicationCredentials': obj.applicationCredentials,
    'bucket': obj.bucket,
    'gkeEnvironment': obj.gkeEnvironment,
    'path': obj.path,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImport
 */
export interface ClusterRecoveryImport {
  /**
   * @schema ClusterRecoveryImport#databases
   */
  readonly databases?: any[];

  /**
   * @schema ClusterRecoveryImport#pgDumpExtraOptions
   */
  readonly pgDumpExtraOptions?: any[];

  /**
   * @schema ClusterRecoveryImport#pgRestoreExtraOptions
   */
  readonly pgRestoreExtraOptions?: any[];

  /**
   * @schema ClusterRecoveryImport#postImportApplicationSQL
   */
  readonly postImportApplicationSql?: any[];

  /**
   * @schema ClusterRecoveryImport#roles
   */
  readonly roles?: any[];

  /**
   * @schema ClusterRecoveryImport#schemaOnly
   */
  readonly schemaOnly?: boolean;

  /**
   * @schema ClusterRecoveryImport#source
   */
  readonly source?: ClusterRecoveryImportSource;

  /**
   * @schema ClusterRecoveryImport#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImport#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImport' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImport(obj: ClusterRecoveryImport | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'databases': obj.databases?.map(y => y),
    'pgDumpExtraOptions': obj.pgDumpExtraOptions?.map(y => y),
    'pgRestoreExtraOptions': obj.pgRestoreExtraOptions?.map(y => y),
    'postImportApplicationSQL': obj.postImportApplicationSql?.map(y => y),
    'roles': obj.roles?.map(y => y),
    'schemaOnly': obj.schemaOnly,
    'source': toJson_ClusterRecoveryImportSource(obj.source),
    'type': obj.type,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackup
 */
export interface ClusterRecoveryPgBaseBackup {
  /**
   * @schema ClusterRecoveryPgBaseBackup#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#owner
   */
  readonly owner?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#secret
   */
  readonly secret?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackup#source
   */
  readonly source?: ClusterRecoveryPgBaseBackupSource;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackup#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackup' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackup(obj: ClusterRecoveryPgBaseBackup | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'database': obj.database,
    'owner': obj.owner,
    'secret': obj.secret,
    'source': toJson_ClusterRecoveryPgBaseBackupSource(obj.source),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPitrTarget
 */
export interface ClusterRecoveryPitrTarget {
  /**
   * @schema ClusterRecoveryPitrTarget#time
   */
  readonly time?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPitrTarget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPitrTarget' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPitrTarget(obj: ClusterRecoveryPitrTarget | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'time': obj.time,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryS3
 */
export interface ClusterRecoveryS3 {
  /**
   * @schema ClusterRecoveryS3#accessKey
   */
  readonly accessKey?: string;

  /**
   * @schema ClusterRecoveryS3#bucket
   */
  readonly bucket?: string;

  /**
   * @schema ClusterRecoveryS3#inheritFromIAMRole
   */
  readonly inheritFromIamRole?: boolean;

  /**
   * @schema ClusterRecoveryS3#path
   */
  readonly path?: string;

  /**
   * @schema ClusterRecoveryS3#region
   */
  readonly region?: string;

  /**
   * @schema ClusterRecoveryS3#secretKey
   */
  readonly secretKey?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryS3#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryS3' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryS3(obj: ClusterRecoveryS3 | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKey': obj.accessKey,
    'bucket': obj.bucket,
    'inheritFromIAMRole': obj.inheritFromIamRole,
    'path': obj.path,
    'region': obj.region,
    'secretKey': obj.secretKey,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoverySecret
 */
export interface ClusterRecoverySecret {
  /**
   * @schema ClusterRecoverySecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoverySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoverySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoverySecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoverySecret(obj: ClusterRecoverySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterMonitoringPodMonitor
 */
export interface ClusterClusterMonitoringPodMonitor {
  /**
   * @schema ClusterClusterMonitoringPodMonitor#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoringPodMonitor#metricRelabelings
   */
  readonly metricRelabelings?: any[];

  /**
   * @schema ClusterClusterMonitoringPodMonitor#relabelings
   */
  readonly relabelings?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoringPodMonitor#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterMonitoringPodMonitor' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterMonitoringPodMonitor(obj: ClusterClusterMonitoringPodMonitor | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enabled': obj.enabled,
    'metricRelabelings': obj.metricRelabelings?.map(y => y),
    'relabelings': obj.relabelings?.map(y => y),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterClusterMonitoringPrometheusRule
 */
export interface ClusterClusterMonitoringPrometheusRule {
  /**
   * @schema ClusterClusterMonitoringPrometheusRule#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ClusterClusterMonitoringPrometheusRule#excludeRules
   */
  readonly excludeRules?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterClusterMonitoringPrometheusRule#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterClusterMonitoringPrometheusRule' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterClusterMonitoringPrometheusRule(obj: ClusterClusterMonitoringPrometheusRule | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enabled': obj.enabled,
    'excludeRules': obj.excludeRules?.map(y => y),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImportSource
 */
export interface ClusterRecoveryImportSource {
  /**
   * @schema ClusterRecoveryImportSource#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryImportSource#host
   */
  readonly host?: string;

  /**
   * @schema ClusterRecoveryImportSource#passwordSecret
   */
  readonly passwordSecret?: ClusterRecoveryImportSourcePasswordSecret;

  /**
   * @schema ClusterRecoveryImportSource#port
   */
  readonly port?: number;

  /**
   * @schema ClusterRecoveryImportSource#sslCertSecret
   */
  readonly sslCertSecret?: ClusterRecoveryImportSourceSslCertSecret;

  /**
   * @schema ClusterRecoveryImportSource#sslKeySecret
   */
  readonly sslKeySecret?: ClusterRecoveryImportSourceSslKeySecret;

  /**
   * @schema ClusterRecoveryImportSource#sslMode
   */
  readonly sslMode?: string;

  /**
   * @schema ClusterRecoveryImportSource#sslRootCertSecret
   */
  readonly sslRootCertSecret?: ClusterRecoveryImportSourceSslRootCertSecret;

  /**
   * @schema ClusterRecoveryImportSource#username
   */
  readonly username?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSource#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImportSource' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImportSource(obj: ClusterRecoveryImportSource | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'database': obj.database,
    'host': obj.host,
    'passwordSecret': toJson_ClusterRecoveryImportSourcePasswordSecret(obj.passwordSecret),
    'port': obj.port,
    'sslCertSecret': toJson_ClusterRecoveryImportSourceSslCertSecret(obj.sslCertSecret),
    'sslKeySecret': toJson_ClusterRecoveryImportSourceSslKeySecret(obj.sslKeySecret),
    'sslMode': obj.sslMode,
    'sslRootCertSecret': toJson_ClusterRecoveryImportSourceSslRootCertSecret(obj.sslRootCertSecret),
    'username': obj.username,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackupSource
 */
export interface ClusterRecoveryPgBaseBackupSource {
  /**
   * @schema ClusterRecoveryPgBaseBackupSource#database
   */
  readonly database?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#host
   */
  readonly host?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#passwordSecret
   */
  readonly passwordSecret?: ClusterRecoveryPgBaseBackupSourcePasswordSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#port
   */
  readonly port?: number;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslCertSecret
   */
  readonly sslCertSecret?: ClusterRecoveryPgBaseBackupSourceSslCertSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslKeySecret
   */
  readonly sslKeySecret?: ClusterRecoveryPgBaseBackupSourceSslKeySecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslMode
   */
  readonly sslMode?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#sslRootCertSecret
   */
  readonly sslRootCertSecret?: ClusterRecoveryPgBaseBackupSourceSslRootCertSecret;

  /**
   * @schema ClusterRecoveryPgBaseBackupSource#username
   */
  readonly username?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSource#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackupSource' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackupSource(obj: ClusterRecoveryPgBaseBackupSource | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'database': obj.database,
    'host': obj.host,
    'passwordSecret': toJson_ClusterRecoveryPgBaseBackupSourcePasswordSecret(obj.passwordSecret),
    'port': obj.port,
    'sslCertSecret': toJson_ClusterRecoveryPgBaseBackupSourceSslCertSecret(obj.sslCertSecret),
    'sslKeySecret': toJson_ClusterRecoveryPgBaseBackupSourceSslKeySecret(obj.sslKeySecret),
    'sslMode': obj.sslMode,
    'sslRootCertSecret': toJson_ClusterRecoveryPgBaseBackupSourceSslRootCertSecret(obj.sslRootCertSecret),
    'username': obj.username,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImportSourcePasswordSecret
 */
export interface ClusterRecoveryImportSourcePasswordSecret {
  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryImportSourcePasswordSecret#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourcePasswordSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImportSourcePasswordSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImportSourcePasswordSecret(obj: ClusterRecoveryImportSourcePasswordSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'key': obj.key,
    'name': obj.name,
    'value': obj.value,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImportSourceSslCertSecret
 */
export interface ClusterRecoveryImportSourceSslCertSecret {
  /**
   * @schema ClusterRecoveryImportSourceSslCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImportSourceSslCertSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImportSourceSslCertSecret(obj: ClusterRecoveryImportSourceSslCertSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImportSourceSslKeySecret
 */
export interface ClusterRecoveryImportSourceSslKeySecret {
  /**
   * @schema ClusterRecoveryImportSourceSslKeySecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslKeySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslKeySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImportSourceSslKeySecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImportSourceSslKeySecret(obj: ClusterRecoveryImportSourceSslKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryImportSourceSslRootCertSecret
 */
export interface ClusterRecoveryImportSourceSslRootCertSecret {
  /**
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryImportSourceSslRootCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryImportSourceSslRootCertSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryImportSourceSslRootCertSecret(obj: ClusterRecoveryImportSourceSslRootCertSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret
 */
export interface ClusterRecoveryPgBaseBackupSourcePasswordSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#create
   */
  readonly create?: boolean;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#value
   */
  readonly value?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourcePasswordSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackupSourcePasswordSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackupSourcePasswordSecret(obj: ClusterRecoveryPgBaseBackupSourcePasswordSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'create': obj.create,
    'key': obj.key,
    'name': obj.name,
    'value': obj.value,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslCertSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackupSourceSslCertSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackupSourceSslCertSecret(obj: ClusterRecoveryPgBaseBackupSourceSslCertSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslKeySecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslKeySecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackupSourceSslKeySecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackupSourceSslKeySecret(obj: ClusterRecoveryPgBaseBackupSourceSslKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret
 */
export interface ClusterRecoveryPgBaseBackupSourceSslRootCertSecret {
  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#key
   */
  readonly key?: string;

  /**
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ClusterRecoveryPgBaseBackupSourceSslRootCertSecret#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ClusterRecoveryPgBaseBackupSourceSslRootCertSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterRecoveryPgBaseBackupSourceSslRootCertSecret(obj: ClusterRecoveryPgBaseBackupSourceSslRootCertSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

