// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface TraefikcrdsProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: TraefikcrdsValues;
}

export class Traefikcrds extends Construct {
  public constructor(scope: Construct, id: string, props: TraefikcrdsProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_TraefikcrdsValues(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'traefik-crds',
      repo: 'https://traefik.github.io/charts',
      version: '1.14.0',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * The Cloud Native Application Proxy
 *
 * @schema traefik-crds
 */
export interface TraefikcrdsValues {
  /**
   * @schema traefik-crds#deleteOnUninstall
   */
  readonly deleteOnUninstall?: boolean;

  /**
   * @schema traefik-crds#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema traefik-crds#gatewayAPI
   */
  readonly gatewayApi?: boolean;

  /**
   * @schema traefik-crds#gatewayAPIExperimental
   */
  readonly gatewayApiExperimental?: boolean;

  /**
   * @schema traefik-crds#global
   */
  readonly global?: { [key: string]: any };

  /**
   * @schema traefik-crds#hub
   */
  readonly hub?: boolean;

  /**
   * @schema traefik-crds#knative
   */
  readonly knative?: boolean;

  /**
   * @schema traefik-crds#traefik
   */
  readonly traefik?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema traefik-crds#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'TraefikcrdsValues' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_TraefikcrdsValues(obj: TraefikcrdsValues | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'deleteOnUninstall': obj.deleteOnUninstall,
    'enabled': obj.enabled,
    'gatewayAPI': obj.gatewayApi,
    'gatewayAPIExperimental': obj.gatewayApiExperimental,
    'global': ((obj.global) === undefined) ? undefined : (Object.entries(obj.global).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'hub': obj.hub,
    'knative': obj.knative,
    'traefik': obj.traefik,
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

