plugin {
 touch_gestures {
  sensitivity = 4.0
  workspace_swipe_fingers = 3
  workspace_swipe_edge = x # disabled
  long_press_delay = 400 #ms
  resize_on_border_long_press = true
  edge_margin = 10
  emulate_touchpad_swipe = false

  hyprgrass-bind=,edge:d:u,exec,kill -34 $(ps -C wvkbd-mobintl)  
  hyprgrass-bind=,longpress:4,togglefloating
  hyprgrass-bind = , edge:r:l, workspace, +1
  hyprgrass-bind = , edge:l:r, workspace, -1
 }
}

exec-once=hyprpaper

$MOD=SUPER

misc {
 force_default_wallpaper=0 # no waifu
}

# for dev work
bind=$MOD,T,exec,alacritty

# keyboard
exec-once=wvkbd-mobintl
