plugin {
 touch_gestures {
  sensitivity = 4.0
  workspace_swipe_fingers = 3
  workspace_swipe_edge = x # disabled
  long_press_delay = 400 #ms
  resize_on_border_long_press = true
  edge_margin = 30
  emulate_touchpad_swipe = false


  # kill keyboard
  hyprgrass-bind=,edge:d:u,exec,kill -34 $(ps -C wvkbd-mobintl)

  # make pressed window float
  hyprgrass-bind=,longpress:2,togglefloating

  # 4 finger swipe down to kill
  hyprgrass-bind=,swipe:3:d,killactive

  # make overview active
  hyprgrass-bind=,edge:u:d,overview:toggle

  hyprgrass-bindm=,longpress:2,movewindow
  hyprgrass-bindm=,longpress:3,resizewindow

  # diagonal down from left to open the appmenu
  hyprgrass-bind =,edge:l:ld,exec,tablet-widgets --launcher
 }

 overview {
   showEmptyWorkspace = false
   showNewWorkspace = true
   exitOnClick = true

   panelHeight = 125
   overrideGaps = false
  }
}

exec-once=hyprpaper

$MOD=SUPER


gestures {
  workspace_swipe = true
  workspace_swipe_cancel_ratio = 0.15
}

misc {
 force_default_wallpaper=0 # no waifu
}

$GAP=4
general {
	gaps_out = $GAP # let the bar draw the left gap
	gaps_in = $GAP
}

decoration {
    blur {
        enabled = true
        size = 3
        passes = 3
        vibrancy = 0.1696
    }
}

# make some ags widgets frosted glass
layerrule=blur,bar
layerrule=ignorezero,bar
layerrule=blur,launcher
layerrule=ignorezero,launcher


# small window for flaoating. we can make it bigger
windowrulev2=size 100 100,floating:1

# for dev work
bind=$MOD,T,exec,alacritty

# keyboard
exec-once=wvkbd-mobintl
