plugin {
 touch_gestures {
  sensitivity = 4.0
  workspace_swipe_fingers = 3
  workspace_swipe_edge = x # disabled
  long_press_delay = 400 #ms
  resize_on_border_long_press = true
  edge_margin = 10
  emulate_touchpad_swipe = false
 }
}

# for dev work
bind = SUPER, T, exec, alacritty

# keyboard
exec-once = wvkbd-mobintl
hyprgrass-bind = , edge:d:u, exec, kill -34 $(ps -C wvkbd-mobintl)
