mutation InsertUser($userId: uuid!, $userName: String!) {
  insert_user_one(object: {
    first_name: $userName, 
    last_name: $userName,
    id: $userId
  }) {
    id
  }
}

mutation InsertGroup($ownerId: uuid!) {
  insert_group_one(object: {
    user_to_groups: {
      data: {
        owner: true, 
        user_id: $ownerId
      }
    }
  }) {
      id
  }
}

mutation DeleteAll {
  delete_group(where: {}) {
    affected_rows
  }
  delete_user(where: {}) {
    affected_rows
  }
  delete_cooking_ingredients(where: {
    group_id: {
      _is_null: true
    }
  }) {
    affected_rows
  }
}

mutation AddUserToGroup($userId: uuid!, $groupId: uuid!) {
 insert_user_to_group_one(object: {
  group_id: $groupId,
  user_id: $userId
}) {
  group {
    id
  }
}
}

mutation Cleanup(
  $userIds: [uuid!],
  $groupIds: [uuid!]
) {
  delete_group(where: {
    id: {
      _in: $groupIds
    }
  }) {
    affected_rows
  }
  delete_user(where: {
    id: {
      _in: $userIds
    }
  }) {
		affected_rows
  }
}