mutation InsertUser($userId: uuid!, $userName: String!) {
  insert_user_one(object: {
    first_name: $userName, 
    last_name:"TEST_USER",
    id: $userId
  }) {
    id
  }
}

mutation InsertGroup {
  insert_group_one(object: {}) {
      id
  }
}


mutation AddUserToGroup($userId: uuid!, $groupId: uuid!) {
 insert_user_to_group_one(object: {
  group_id: $groupId,
  user_id: $userId
}) {
  group {
    id
  }
}
}

mutation Cleanup(
  $userIds: [uuid!],
  $groupIds: [uuid!]
) {
  delete_group(where: {
    id: {
      _in: $groupIds
    }
  }) {
    affected_rows
  }
  delete_user(where: {
    id: {
      _in: $userIds
    }
  }) {
		affected_rows
  }
}