-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "cooking"."ingredients" add column "public" boolean
--  null default 'false';
