mutation InsertMockRecipe($groupId: uuid!) {
	insert_cooking_recipe_one(object: {
    group_id: $groupId,
    name: "TEST RECIPE", 
    ingredients: {
      data: {
            name: "FAKE",
        }
      }
    
  }) {
    id,
    ingredients {
      id
    }
  }
}

query GetRecipe($id: uuid!) {
  cooking_recipe_by_pk(id: $id) {
    id
  }
}

mutation DeleteRecipe($id: uuid!) {
  delete_cooking_recipe_by_pk(id: $id) {
    id
  }
}

query GetIngredient($id: uuid!) {
  cooking_ingredients_by_pk(id: $id) {
    id
  }
}
